# -*- coding: utf-8 -*-
"""project_2_supervised_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/131lWwqYjgTBFxiFJkej--BFOkeqOekeN

# Supervised Learning Methods: A Practical Project for SPARK Students

## Chapter 1: Introduction to Supervised Learning and Data Loading

Welcome, SPARK students! In this project, we will explore various supervised learning methods using a real-world dataset. Supervised learning is a type of machine learning where we train a model on labeled data (input features and corresponding output labels) to predict outcomes for new, unseen data.

### Project Goal:
Your task is to build and evaluate different supervised learning models to predict whether a user will click on an advertisement based on their demographic information.

### The Dataset:
We will be using the `social_media_advertising.csv` dataset, which contains information about users, their demographics, and whether they clicked on an ad. The dataset can be found [here](https://github.com/katjanieberle/sparks/blob/main/social_media_advertising.csv). Let's start by loading this data into our notebook.
"""



"""### Exercise 1.1: Load the Dataset

Your first step is to load the `social_media_advertising.csv` dataset into a pandas DataFrame. Use the provided URL to directly read the CSV file. After loading, display the first 5 rows to get a glimpse of the data.
"""

import pandas as pd

# Define the URL for the dataset
data_url = 'https://raw.githubusercontent.com/katjanieberle/sparks/main/social_media_advertising.csv'

# Students: Load the dataset into a pandas DataFrame
# Hint: Use pd.read_csv()

df = pd.read_csv(data_url)

# Students: Display the first 5 rows of the DataFrame
# Hint: Use df.head()
display(df.head())

"""### Exercise 1.2: Initial Data Exploration

After loading the data, it's crucial to understand its structure, data types, and identify any missing values. This step helps us in planning the necessary preprocessing steps.

**Tasks:**
1.  Display a concise summary of the DataFrame, including data types and non-null values count.
2.  Generate descriptive statistics of the numerical columns to understand their distribution (e.g., mean, min, max, standard deviation).
"""

# Students: Display a concise summary of the DataFrame
# Hint: Use df.info()
print("\n--- DataFrame Info ---")
df.info()

# Students: Generate descriptive statistics of the numerical columns
# Hint: Use df.describe()
print("\n--- Descriptive Statistics ---")
display(df.describe())

"""## Chapter 2: Data Preprocessing

Data preprocessing is a vital step in any machine learning pipeline. It involves cleaning and transforming raw data into a format suitable for model training. In this chapter, we will focus on:

1.  **Identifying the Target Variable**: Determining what we want to predict.
2.  **Handling 'Acquisition_Cost'**: Converting it into a numerical format.
3.  **Encoding Categorical Variables**: Transforming text-based categories into numerical representations that machine learning algorithms can understand.

### Exercise 2.1: Identify the Target Variable

In this project, we aim to predict whether a user will click on an advertisement. Based on the dataset description and column names, identify which column represents this outcome. This will be our target variable (`y`). The remaining relevant columns will be our features (`X`).

**Task:** State the name of the target variable.
"""

# Students: Identify and assign the target variable
# Hint: Look for a column that indicates whether an ad was 'clicked' or a similar outcome.

target_variable = 'Clicks'
print(f"The identified target variable is: {target_variable}")

"""### Exercise 2.2: Clean and Convert 'Acquisition_Cost'

Looking at `df.info()`, you might have noticed that the `Acquisition_Cost` column is of type `object`, even though it represents a numerical value. This is likely due to the presence of a currency symbol (e.g., '$').

**Tasks:**
1.  Remove the '$' sign from the `Acquisition_Cost` column.
2.  Convert the `Acquisition_Cost` column to a numeric data type (e.g., float).
3.  Verify the data type conversion using `df.info()`.
"""

# Students: Remove the '$' sign and convert 'Acquisition_Cost' to numeric
# Hint: Use .str.replace() and pd.to_numeric()

df['Acquisition_Cost'] = df['Acquisition_Cost'].str.replace('$', '', regex=False)
df['Acquisition_Cost'] = pd.to_numeric(df['Acquisition_Cost'])

# Students: Verify the data type conversion
print("\n--- DataFrame Info after Acquisition_Cost conversion ---")
df.info()

"""### Exercise 2.3: Encode Categorical Variables

Many machine learning algorithms require numerical input. Our dataset contains several categorical columns (e.g., `Target_Audience`, `Channel_Used`, `Location`). We need to convert these into a numerical format.

**One-Hot Encoding** is a common technique for this, where each category is transformed into a new binary column. For example, if a `Location` column has 'New York' and 'Los Angeles', it would become two new columns, `Location_New York` and `Location_Los Angeles`, with 1s and 0s.

**Tasks:**
1.  Identify all categorical columns (object dtype) in the DataFrame, excluding 'Date' and 'Company' as they are not typically used as direct features in their raw form for classification problems without further feature engineering.
2.  Apply one-hot encoding to these categorical columns using `pd.get_dummies()`.
3.  Display the first few rows of the new DataFrame to see the effect of encoding.
"""

# Students: Identify categorical columns to encode
# Exclude 'Date' and 'Company' for this exercise.

categorical_cols = df.select_dtypes(include='object').columns.tolist()
categorical_cols = [col for col in categorical_cols if col not in ['Date', 'Company']]

print(f"Categorical columns to encode: {categorical_cols}")

# Students: Apply one-hot encoding
# Hint: Use pd.get_dummies() on the original DataFrame and then drop the original categorical columns, or directly pass the list of columns to get_dummies

df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True) # drop_first to avoid multicollinearity

# Students: Display the first few rows of the encoded DataFrame
display(df_encoded.head())

"""## Chapter 3: Feature Selection and Data Splitting

Now that our data is preprocessed, the next steps are to select the features we will use for training our models and then split the data into training and testing sets.

### Exercise 2.4: Create a Binary Classification Target Variable

During the previous step, we identified that the `Clicks` column always has values greater than 0, meaning all ad campaigns in this dataset resulted in at least some clicks. This prevents us from directly creating a 'clicked vs. not clicked' binary target, as there's no 'not clicked' class.

To proceed with binary classification methods (like Logistic Regression, KNN, Decision Trees, Random Forests), we need a target variable with at least two classes. A common approach when a natural binary outcome is not present in the data but a continuous outcome is, is to create a binary target based on a threshold of the continuous variable.

**Let's redefine our classification goal for this dataset:** Instead of predicting if an ad was clicked (which it always was), we will predict if an ad received a **'High Number of Clicks'** versus a **'Low Number of Clicks'**.

**Tasks:**
1.  Calculate the median value of the `Clicks` column. This will serve as our threshold.
2.  Create a new column named `High_Clicks` in our `df_encoded` DataFrame.
3.  Assign `1` to `High_Clicks` if the value in the `Clicks` column is **greater than the median clicks**, and `0` otherwise.
4.  Display the value counts for the new `High_Clicks` column to see the distribution of our target classes. This should now show two distinct classes.
"""

# Students: Create a binary 'High_Clicks' target variable
# As discussed, the original 'Clicks' column always has values > 0.
# To create a meaningful binary classification problem (e.g., 'high clicks' vs 'low clicks'),
# we will define 'High_Clicks' based on whether the number of Clicks is above the median.

median_clicks = df_encoded['Clicks'].median()
print(f"Median Clicks: {median_clicks}")

df_encoded['High_Clicks'] = (df_encoded['Clicks'] > median_clicks).astype(int)

# Students: Display the value counts of the new 'High_Clicks' column
print("\n--- Value counts for the new 'High_Clicks' target variable ---")
display(df_encoded['High_Clicks'].value_counts())

# We will use 'High_Clicks' as our target variable 'y' for classification tasks.

"""## Chapter 3: Feature Selection and Data Splitting

With our data preprocessed and our binary target variable created, the next crucial steps are to select the features (independent variables, `X`) that will be used to train our models and then split the dataset into training and testing sets. This split ensures that we can evaluate our model's performance on unseen data, providing an unbiased estimate of its generalization capability.

### Exercise 3.1: Define Features (X) and Target (y)

Now, let's separate our DataFrame into features (`X`) and the target variable (`y`). For classification tasks, our target `y` will be the newly created `High_Clicks` column.

**Tasks:**
1.  Define `y` as our `High_Clicks` column.
2.  Define `X` by dropping the `Campaign_ID`, `Date`, `Company`, and original `Clicks` columns (as we've created `High_Clicks` from it), and `High_Clicks` itself from `df_encoded`. These columns are either identifiers, temporal (and not yet engineered as features), or the target variables.
3.  Display the shape of `X` and `y` to confirm their dimensions.
"""

# Students: Define the target variable (y)
# We use 'High_Clicks' as our binary target for classification
y = df_encoded['High_Clicks']

# Students: Define the features (X) by dropping irrelevant columns
# Hint: Use .drop() and specify axis=1 for columns
# We drop 'Clicks' (the original continuous target) and 'High_Clicks' (the new binary target) from features.
columns_to_drop = ['Campaign_ID', 'Date', 'Company', 'Clicks', 'High_Clicks']
X = df_encoded.drop(columns=columns_to_drop)

# Students: Display the shape of X and y
print(f"Shape of features (X): {X.shape}")
print(f"Shape of target (y): {y.shape}")

"""### Exercise 3.2: Split Data into Training and Testing Sets

It's standard practice to split the data into a training set and a testing set. The training set is used to train the model, and the testing set is used to evaluate its performance on unseen data. We will use a 80/20 split (80% for training, 20% for testing) and ensure reproducibility with a `random_state`.

**Tasks:**
1.  Import the `train_test_split` function from `sklearn.model_selection`.
2.  Split `X` and `y` into `X_train`, `X_test`, `y_train`, and `y_test`.
3.  Use `test_size=0.2` and `random_state=42`.
4.  Display the shapes of the resulting training and testing sets.
"""

from sklearn.model_selection import train_test_split

# Students: Split the data into training and testing sets
# Hint: X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Students: Display the shapes of the training and testing sets
print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

"""## Chapter 4: Supervised Learning Models - Logistic Regression

Now that our data is prepared, we can start building and evaluating our first supervised learning model: Logistic Regression. Despite its name, Logistic Regression is a classification algorithm, widely used for binary classification problems like ours (predicting 'high clicks' or 'low clicks'). It models the probability that a given input belongs to a particular class.

### Exercise 4.1: Train a Logistic Regression Model

**Tasks:**
1.  Import `LogisticRegression` from `sklearn.linear_model`.
2.  Initialize a `LogisticRegression` model. For simplicity, we'll use default parameters for now.
3.  Train the model using the training data (`X_train`, `y_train`).
"""

from sklearn.linear_model import LogisticRegression

# Students: Initialize the Logistic Regression model
# Hint: model = LogisticRegression(random_state=42, solver='liblinear')

# We'll use 'liblinear' solver for smaller datasets and for handling L1/L2 regularization
# and set a random_state for reproducibility.
model = LogisticRegression(random_state=42, solver='liblinear')

# Students: Train the model using the training data
model.fit(X_train, y_train)

print("Logistic Regression model trained successfully!")

"""### Exercise 4.2: Make Predictions and Evaluate the Model

After training, we need to evaluate how well our model performs on unseen data. We will use the test set for this purpose and look at common classification metrics.

**Tasks:**
1.  Make predictions on the `X_test` data.
2.  Import classification metrics: `accuracy_score`, `precision_score`, `recall_score`, and `f1_score` from `sklearn.metrics`.
3.  Calculate and print the accuracy, precision, recall, and F1-score of the model.
"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Students: Make predictions on the test set
y_pred = model.predict(X_test)

# Students: Calculate and print evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f"\n--- Model Evaluation (Logistic Regression) ---")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")

"""## Chapter 5: Supervised Learning Models - K-Nearest Neighbors (KNN)

K-Nearest Neighbors (KNN) is a non-parametric, lazy learning algorithm used for both classification and regression. In classification, a new data point is classified by a majority vote of its `k` nearest neighbors. The 'distance' between data points is usually calculated using Euclidean distance. KNN is easy to understand and implement, but can be computationally expensive for large datasets and sensitive to the scale of features.

### Exercise 5.1: Feature Scaling for KNN

KNN algorithms are distance-based, meaning they are highly sensitive to the scale of the features. Features with larger values can dominate the distance calculation. To prevent this, we need to scale our features so that they all contribute proportionally to the distance.

**Tasks:**
1.  Import `StandardScaler` from `sklearn.preprocessing`.
2.  Initialize a `StandardScaler`.
3.  Fit the scaler on `X_train` and transform both `X_train` and `X_test`.
4.  Display the first few rows of the scaled training data to observe the changes.
"""

from sklearn.preprocessing import StandardScaler

# Students: Initialize the StandardScaler
scaler = StandardScaler()

# Students: Fit the scaler on the training data and transform both training and test data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Convert back to DataFrame for easier inspection (optional, but good for visualization)
X_train_scaled_df = pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_test_scaled_df = pd.DataFrame(X_test_scaled, columns=X_test.columns)

print("\n--- First 5 rows of scaled X_train data ---")
display(X_train_scaled_df.head())

"""### Exercise 5.2: Train a K-Nearest Neighbors Model

Now, with our scaled features, we can train a KNN classifier.

**Tasks:**
1.  Import `KNeighborsClassifier` from `sklearn.neighbors`.
2.  Initialize a `KNeighborsClassifier` model. Start with a common value for `n_neighbors`, for example, `n_neighbors=5`.
3.  Train the model using the **scaled** training data (`X_train_scaled`, `y_train`).
"""

from sklearn.neighbors import KNeighborsClassifier

# Students: Initialize the KNN model with n_neighbors=5
knn_model = KNeighborsClassifier(n_neighbors=5)

# Students: Train the KNN model using the scaled training data
knn_model.fit(X_train_scaled, y_train)

print("K-Nearest Neighbors model trained successfully!")

"""### Exercise 5.3: Make Predictions and Evaluate the KNN Model

Let's evaluate the performance of our KNN model on the scaled test data.

**Tasks:**
1.  Make predictions on the **scaled** `X_test_scaled` data.
2.  Calculate and print the accuracy, precision, recall, and F1-score of the KNN model.
"""

# Students: Make predictions on the scaled test set
y_pred_knn = knn_model.predict(X_test_scaled)

# Students: Calculate and print evaluation metrics for KNN
accuracy_knn = accuracy_score(y_test, y_pred_knn)
precision_knn = precision_score(y_test, y_pred_knn)
recall_knn = recall_score(y_test, y_pred_knn)
f1_knn = f1_score(y_test, y_pred_knn)

print(f"\n--- Model Evaluation (K-Nearest Neighbors) ---")
print(f"Accuracy: {accuracy_knn:.4f}")
print(f"Precision: {precision_knn:.4f}")
print(f"Recall: {recall_knn:.4f}")
print(f"F1-Score: {f1_knn:.4f}")

"""## Chapter 5: Supervised Learning Models - K-Nearest Neighbors (KNN)

K-Nearest Neighbors (KNN) is a non-parametric, lazy learning algorithm used for both classification and regression. In classification, a new data point is classified by a majority vote of its `k` nearest neighbors. The 'distance' between data points is usually calculated using Euclidean distance. KNN is easy to understand and implement, but can be computationally expensive for large datasets and sensitive to the scale of features.

### Exercise 5.1: Feature Scaling for KNN

KNN algorithms are distance-based, meaning they are highly sensitive to the scale of the features. Features with larger values can dominate the distance calculation. To prevent this, we need to scale our features so that they all contribute proportionally to the distance.

**Tasks:**
1.  Import `StandardScaler` from `sklearn.preprocessing`.
2.  Initialize a `StandardScaler`.
3.  Fit the scaler on `X_train` and transform both `X_train` and `X_test`.
4.  Display the first few rows of the scaled training data to observe the changes.
"""

from sklearn.preprocessing import StandardScaler

# Students: Initialize the StandardScaler
scaler = StandardScaler()

# Students: Fit the scaler on the training data and transform both training and test data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Convert back to DataFrame for easier inspection (optional, but good for visualization)
X_train_scaled_df = pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_test_scaled_df = pd.DataFrame(X_test_scaled, columns=X_test.columns)

print("\n--- First 5 rows of scaled X_train data ---")
display(X_train_scaled_df.head())

"""### Exercise 5.2: Train a K-Nearest Neighbors Model

Now, with our scaled features, we can train a KNN classifier.

**Tasks:**
1.  Import `KNeighborsClassifier` from `sklearn.neighbors`.
2.  Initialize a `KNeighborsClassifier` model. Start with a common value for `n_neighbors`, for example, `n_neighbors=5`.
3.  Train the model using the **scaled** training data (`X_train_scaled`, `y_train`).
"""

from sklearn.neighbors import KNeighborsClassifier

# Students: Initialize the KNN model with n_neighbors=5
knn_model = KNeighborsClassifier(n_neighbors=5)

# Students: Train the KNN model using the scaled training data
knn_model.fit(X_train_scaled, y_train)

print("K-Nearest Neighbors model trained successfully!")

"""### Exercise 5.3: Make Predictions and Evaluate the KNN Model

Let's evaluate the performance of our KNN model on the scaled test data.

**Tasks:**
1.  Make predictions on the **scaled** `X_test_scaled` data.
2.  Calculate and print the accuracy, precision, recall, and F1-score of the KNN model.
"""

# Students: Make predictions on the scaled test set
y_pred_knn = knn_model.predict(X_test_scaled)

# Students: Calculate and print evaluation metrics for KNN
accuracy_knn = accuracy_score(y_test, y_pred_knn)
precision_knn = precision_score(y_test, y_pred_knn)
recall_knn = recall_score(y_test, y_pred_knn)
f1_knn = f1_score(y_test, y_pred_knn)

print(f"\n--- Model Evaluation (K-Nearest Neighbors) ---")
print(f"Accuracy: {accuracy_knn:.4f}")
print(f"Precision: {precision_knn:.4f}")
print(f"Recall: {recall_knn:.4f}")
print(f"F1-Score: {f1_knn:.4f}")

"""## Chapter 6: Supervised Learning Models - Decision Trees

Decision Trees are a non-parametric supervised learning method used for classification and regression tasks. The goal is to create a model that predicts the value of a target variable by learning simple decision rules inferred from the data features. A decision tree is built by splitting the data into subsets based on the most significant attribute at each node, recursively repeating this process until the data can no longer be split or a stopping criterion is met.

### Exercise 6.1: Train a Decision Tree Classifier

Decision Trees can work with unscaled data, but feature scaling is often beneficial for overall model performance and consistency in a pipeline. For this exercise, we will use the unscaled `X_train` and `X_test` data to demonstrate a basic Decision Tree, but remember that scaling can be important.

**Tasks:**
1.  Import `DecisionTreeClassifier` from `sklearn.tree`.
2.  Initialize a `DecisionTreeClassifier` model. Use `random_state=42` for reproducibility.
3.  Train the model using the original (unscaled) training data (`X_train`, `y_train`).
"""

from sklearn.tree import DecisionTreeClassifier

# Students: Initialize the Decision Tree Classifier model
# Use random_state for reproducibility
dt_model = DecisionTreeClassifier(random_state=42)

# Students: Train the model using the unscaled training data
dt_model.fit(X_train, y_train)

print("Decision Tree Classifier trained successfully!")

"""### Exercise 6.2: Make Predictions and Evaluate the Decision Tree Model

Let's evaluate the performance of our Decision Tree model on the test data.

**Tasks:**
1.  Make predictions on the `X_test` data.
2.  Calculate and print the accuracy, precision, recall, and F1-score of the Decision Tree model.
"""

# Students: Make predictions on the test set
y_pred_dt = dt_model.predict(X_test)

# Students: Calculate and print evaluation metrics for Decision Tree
accuracy_dt = accuracy_score(y_test, y_pred_dt)
precision_dt = precision_score(y_test, y_pred_dt)
recall_dt = recall_score(y_test, y_pred_dt)
f1_dt = f1_score(y_test, y_pred_dt)

print(f"\n--- Model Evaluation (Decision Tree) ---")
print(f"Accuracy: {accuracy_dt:.4f}")
print(f"Precision: {precision_dt:.4f}")
print(f"Recall: {recall_dt:.4f}")
print(f"F1-Score: {f1_dt:.4f}")

"""## Chapter 7: Supervised Learning Models - Random Forest

Random Forest is an ensemble learning method for classification and regression that operates by constructing a multitude of decision trees at training time. For classification tasks, the output of the random forest is the class selected by most trees. It's known for its high accuracy and ability to handle large datasets with high dimensionality.

### Exercise 7.1: Train a Random Forest Classifier

Similar to Decision Trees, Random Forests generally do not require feature scaling. We will train a Random Forest model on our original (unscaled) features.

**Tasks:**
1.  Import `RandomForestClassifier` from `sklearn.ensemble`.
2.  Initialize a `RandomForestClassifier` model. Use `n_estimators=100` (number of trees) and `random_state=42` for reproducibility.
3.  Train the model using the original (unscaled) training data (`X_train`, `y_train`).
"""

from sklearn.ensemble import RandomForestClassifier

# Students: Initialize the Random Forest Classifier model
# Use n_estimators (number of trees) and random_state for reproducibility
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

# Students: Train the model using the unscaled training data
rf_model.fit(X_train, y_train)

print("Random Forest Classifier trained successfully!")

"""### Exercise 7.2: Make Predictions and Evaluate the Random Forest Model

Finally, let's evaluate the performance of our Random Forest model.

**Tasks:**
1.  Make predictions on the `X_test` data.
2.  Calculate and print the accuracy, precision, recall, and F1-score of the Random Forest model.
"""

# Students: Make predictions on the test set
y_pred_rf = rf_model.predict(X_test)

# Students: Calculate and print evaluation metrics for Random Forest
accuracy_rf = accuracy_score(y_test, y_pred_rf)
precision_rf = precision_score(y_test, y_pred_rf)
recall_rf = recall_score(y_test, y_pred_rf)
f1_rf = f1_score(y_test, y_pred_rf)

print(f"\n--- Model Evaluation (Random Forest) ---")
print(f"Accuracy: {accuracy_rf:.4f}")
print(f"Precision: {precision_rf:.4f}")
print(f"Recall: {recall_rf:.4f}")
print(f"F1-Score: {f1_rf:.4f}")