# -*- coding: utf-8 -*-
"""SPARKS_NLP_sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PMk94ghhOq0xL-wi5j1XC7V9YNTe4gY5
"""



"""## Chapter 1: Natural Language Processing and Text Mining

### Introduction

Welcome to a fascinating journey into the world of **Natural Language Processing (NLP)** and **Text Mining**! As future data scientists, understanding how to extract insights from human language is an indispensable skill. The digital age generates an unprecedented amount of text data—social media posts, customer reviews, news articles, scientific papers, and much more. NLP and Text Mining provide the tools to make sense of this unstructured data.

In this chapter, we will cover:

*   **Fundamentals of NLP**: Basic concepts and techniques to process human language.
*   **Text Representation**: How to convert text into a format that machine learning models can understand.
*   **Text Mining Applications**: Practical examples like sentiment analysis and topic modeling.

Let's get started!

### What is Natural Language Processing (NLP)?

**Natural Language Processing (NLP)** is a subfield of artificial intelligence, computer science, and linguistics concerned with the interactions between computers and human (natural) languages. Its goal is to enable computers to understand, interpret, and generate human language in a valuable way.

Think about features like spam detection, translation services (e.g., Google Translate), voice assistants (e.g., Siri, Alexa), and sentiment analysis on product reviews—these are all powered by NLP.

### 1. Text Preprocessing: The First Step

Before we can analyze text, it almost always needs to be cleaned and transformed. This crucial step is called **text preprocessing**. It helps to reduce noise, standardize the data, and prepare it for further analysis. Key preprocessing steps include:

*   **Tokenization**
*   **Stop Word Removal**
*   **Stemming and Lemmatization**
*   **Lowercasing and Punctuation Removal**

Let's begin with **Tokenization**.

#### 1.1 Tokenization

**Tokenization** is the process of breaking down a text into smaller units called **tokens**. These tokens can be words, phrases, symbols, or even characters. It's often the very first step in any NLP pipeline. Each token is then treated as a single unit for further analysis.

For example, the sentence "Hello, world!" could be tokenized into `['Hello', ',', 'world', '!']`.

We'll use the `NLTK` (Natural Language Toolkit) library, a powerful library for working with human language data, and `SpaCy`, an industrial-strength NLP library, to demonstrate tokenization.
"""

# First, we need to install the NLTK library if you haven't already.
# This command is typically run once per session or when setting up the environment.
# !pip install nltk

# We also need to download necessary NLTK data, like the 'punkt' tokenizer models.
import nltk
nltk.download('punkt_tab') # This line is added to download the necessary resource

import nltk
from nltk.tokenize import word_tokenize, sent_tokenize

text = """Natural Language Processing (NLP) is a subfield of artificial intelligence. It's concerned with the interaction between computers and human language. We will learn a lot today!"""

# Word Tokenization
words = word_tokenize(text)
print("\n--- Word Tokens ---")
print(words[:10]) # Displaying first 10 words for brevity

# Sentence Tokenization
sentences = sent_tokenize(text)
print("\n--- Sentence Tokens ---")
print(sentences)

# --- Using SpaCy for Tokenization ---
# !pip install spacy
# !python -m spacy download en_core_web_sm

import spacy

# Load the English language model
# If you haven't downloaded it, run: !python -m spacy download en_core_web_sm
nlp = spacy.load("en_core_web_sm")

doc = nlp(text)

# SpaCy's tokenization also includes more sophisticated linguistic features
print("\n--- SpaCy Tokens (first 10) ---")
for token in doc[:10]:
    print(f"Token: {token.text}, Lemma: {token.lemma_}, POS: {token.pos_}, Is Stop: {token.is_stop}")

"""#### 1.2 Stop Word Removal

**Stop words** are common words that carry little significant meaning in the context of text analysis (e.g., "the", "is", "a", "an", "in"). Removing them can help reduce the dimensionality of your data, speed up processing, and improve the focus on more important, content-bearing words.

However, it's important to consider your specific NLP task. For some applications, like sentiment analysis, stop words might carry contextual meaning (e.g., "not good"), so careful consideration is needed before removal.

Let's see how to remove stop words using NLTK.
"""

# Download the NLTK stop words corpus if you haven't already
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

text = "This is an example sentence, demonstrating the removal of common stop words."

# Get English stop words
stop_words = set(stopwords.words('english'))

# Tokenize the text
words = word_tokenize(text)

# Filter out stop words
filtered_words = [word for word in words if word.lower() not in stop_words]

print("Original words:", words)
print("Filtered words (after stop word removal):", filtered_words)

# Let's demonstrate with a more complex sentence and SpaCy's built-in stop word functionality
import spacy
nlp = spacy.load("en_core_web_sm")

text_spacy = "The quick brown fox jumps over the lazy dog and runs away. It is a beautiful day!"
doc_spacy = nlp(text_spacy)

# Filter out stop words and punctuation using SpaCy
filtered_tokens_spacy = [token.text for token in doc_spacy if not token.is_stop and not token.is_punct]

print("\n--- SpaCy Stop Word Removal ---")
print("Original text:", text_spacy)
print("Filtered tokens (SpaCy):", filtered_tokens_spacy)

"""#### 1.3 Stemming and Lemmatization

Words often appear in various morphological forms (e.g., "run", "runs", "running", "ran"). **Stemming** and **Lemmatization** are techniques to reduce these words to a common base form. This helps in standardizing words and reduces the size of the vocabulary, which can improve the performance of many NLP models.

*   **Stemming**: A simpler, rule-based process that chops off suffixes from words. It often results in word stems that are not actual words themselves (e.g., "running" -> "runn"). It's faster but less accurate.

*   **Lemmatization**: A more sophisticated process that uses vocabulary and morphological analysis to return the base or dictionary form of a word, known as a **lemma**. The lemma is always a valid word (e.g., "running" -> "run", "better" -> "good"). It's slower but more accurate.

We'll demonstrate both using NLTK and SpaCy.
"""

import nltk
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.tokenize import word_tokenize

# Download necessary NLTK data for lemmatization
nltk.download('wordnet')
nltk.download('omw-1.4') # Open Multilingual Wordnet, often needed for wordnet

# Sample text
text = "The quick brown foxes are running and jumping. They were better at swimming than flying."
words = word_tokenize(text)

print("Original words:", words)

# --- Stemming with NLTK's PorterStemmer ---
porter = PorterStemmer()
stemmed_words = [porter.stem(word) for word in words]
print("\nStemmed words (Porter Stemmer):", stemmed_words)

# --- Lemmatization with NLTK's WordNetLemmatizer ---
# Note: Lemmatization often requires part-of-speech (POS) tags for better accuracy.
# For simplicity, we'll do basic lemmatization without POS for now.
lemmatizer = WordNetLemmatizer()
lemmatized_words = [lemmatizer.lemmatize(word) for word in words]
print("Lemmatized words (WordNetLemmatizer - basic):", lemmatized_words)

# --- Lemmatization with SpaCy (more robust, includes POS) ---
import spacy
nlp = spacy.load("en_core_web_sm")

doc = nlp(text)

print("\n--- SpaCy Lemmatization (with POS information) ---")
for token in doc:
    print(f"Token: {token.text}, Lemma: {token.lemma_}, POS: {token.pos_}")

spacy_lemmas = [token.lemma_ for token in doc]
print("\nSpaCy Lemmas (list):", spacy_lemmas)

"""#### 1.4 Lowercasing and Punctuation Removal

**Lowercasing** converts all text to a uniform lower-case format. This helps treat words like "Apple" and "apple" as the same token, which is often desirable in NLP tasks to reduce vocabulary size and avoid treating case variations as distinct words.

**Punctuation Removal** eliminates characters like periods, commas, exclamation marks, etc. While punctuation can sometimes carry meaning (e.g., in sentiment analysis), for many tasks, it's considered noise that can interfere with word-based analysis. Removing it simplifies the text and focuses on the words themselves.
"""

import re
import string
from nltk.tokenize import word_tokenize

text = "Hello World! This is an Example sentence with some Punctuation, like commas and periods. How are you doing?"

print("Original Text:\n", text)

# --- Lowercasing ---
lowercase_text = text.lower()
print("\nLowercased Text:\n", lowercase_text)

# --- Punctuation Removal (using string.punctuation and re) ---
# Method 1: Using str.translate and str.maketrans
translator = str.maketrans('', '', string.punctuation)
no_punct_text_1 = text.translate(translator)
print("\nText without punctuation (Method 1):\n", no_punct_text_1)

# Method 2: Using Regular Expressions
no_punct_text_2 = re.sub(r'[%s]' % re.escape(string.punctuation), '', text)
print("Text without punctuation (Method 2):\n", no_punct_text_2)

# --- Combining Lowercasing and Punctuation Removal ---
processed_text = lowercase_text.translate(translator) # Apply to already lowercased text
print("\nLowercased and Punctuation Removed Text:\n", processed_text)

# Tokenize the final processed text
final_tokens = word_tokenize(processed_text)
print("\nFinal Tokens after all preprocessing (NLTK):\n", final_tokens)

# --- SpaCy's approach (already covers this with token.is_punct and token.lower_) ---
import spacy
nlp = spacy.load("en_core_web_sm")

doc = nlp(text)

spacy_processed_tokens = [token.lemma_.lower() for token in doc if not token.is_stop and not token.is_punct]
print("\nSpaCy processed tokens (Lowercased, no Punctuation, no Stop Words, Lemmatized):\n", spacy_processed_tokens)

"""## 2. Text Representation: Turning Words into Numbers

Computers don't understand text directly; they work with numbers. **Text representation** is the process of converting raw text into numerical vectors that machine learning algorithms can process. This is a critical step, as the quality of your representation significantly impacts the performance of your models.

We will explore several common methods:

*   **Bag-of-Words (BoW)**
*   **TF-IDF (Term Frequency-Inverse Document Frequency)**
*   **Word Embeddings (e.g., Word2Vec, GloVe)** - (brief introduction, deeper dive later)

Let's start with the simplest yet foundational model: **Bag-of-Words**.

#### 2.1 Bag-of-Words (BoW)

The **Bag-of-Words (BoW)** model is a simple and widely used technique for text representation. It represents a piece of text (like a document or a sentence) as a bag (multiset) of its words, disregarding grammar and even word order, but keeping track of word frequencies.

**How it works:**

1.  **Vocabulary Creation:** A list of all unique words across the entire corpus (collection of documents) is created.
2.  **Vectorization:** Each document is then represented as a numerical vector where each dimension corresponds to a unique word in the vocabulary. The value in each dimension is typically the count of how many times that word appears in the document.

**Example:**

*   Document 1: "I like cats and dogs."
*   Document 2: "I like dogs, but not cats."

**Vocabulary:** `['I', 'like', 'cats', 'and', 'dogs', 'but', 'not']`

**Vector Representation:**

*   Document 1: `[1, 1, 1, 1, 1, 0, 0]` (counts of 'I', 'like', 'cats', 'and', 'dogs', 'but', 'not')
*   Document 2: `[1, 1, 1, 0, 1, 1, 1]` (counts of 'I', 'like', 'cats', 'and', 'dogs', 'but', 'not')

We will use `Scikit-learn`'s `CountVectorizer` to implement the Bag-of-Words model.
"""

from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# Sample documents (after preprocessing like lowercasing, punctuation removal, etc.)
documents = [
    "The cat sat on the mat",
    "The dog ate the cat",
    "The cat is a pet"
]

# Create a CountVectorizer object
# It will build a vocabulary and convert documents to feature vectors
vectorizer = CountVectorizer()

# Fit the vectorizer to the documents and transform them into BoW vectors
X = vectorizer.fit_transform(documents)

# Get the feature names (words in the vocabulary)
feature_names = vectorizer.get_feature_names_out()

print("Vocabulary (Feature Names):", feature_names)
print("\nShape of the BoW matrix (Documents x Vocabulary Size):", X.shape)

# Convert the sparse matrix to a dense array for better readability
dense_array = X.toarray()

# Display the BoW matrix using a Pandas DataFrame for clarity
bow_df = pd.DataFrame(dense_array, columns=feature_names, index=[f'Document {i+1}' for i in range(len(documents))])
print("\nBag-of-Words Matrix:")
print(bow_df)

# Example for a new document
new_document = ["A cat is a furry animal"]
new_document_vector = vectorizer.transform(new_document)
new_document_df = pd.DataFrame(new_document_vector.toarray(), columns=feature_names, index=['New Document'])
print("\nBag-of-Words Representation for a new document:")
print(new_document_df)

"""#### 2.2 TF-IDF (Term Frequency-Inverse Document Frequency)

**TF-IDF** is another very popular technique for text representation that addresses one of the major drawbacks of plain Bag-of-Words: it assigns weights to words based on their importance to a document in a collection or corpus.

TF-IDF is composed of two terms:

1.  **Term Frequency (TF):** This measures how frequently a term appears in a document. Since longer documents may have a term appear more often than shorter ones, TF is often normalized by dividing the raw count by the total number of words in the document:
    
    $$ \text{TF}(t,d) = \frac{\text{Number of times term } t \text{ appears in document } d}{\text{Total number of terms in document } d} $$

2.  **Inverse Document Frequency (IDF):** This measures how important a term is across the whole corpus. Rare terms across the corpus have a high IDF score, while common terms (like stop words) have a low IDF score. It helps to penalize words that appear too frequently across many documents.
    
    $$ \text{IDF}(t,D) = \log\left(\frac{\text{Total number of documents in corpus } D}{\text{Number of documents with term } t \text{ in them}} \right) $$

    (A small smoothing factor, typically 1, is often added to the denominator to avoid division by zero for terms not in the corpus, and log is used to dampen the effect of IDF.)

Finally, the TF-IDF score is calculated by multiplying TF and IDF:

$$ \text{TF-IDF}(t,d,D) = \text{TF}(t,d) \times \text{IDF}(t,D) $$

This means a high TF-IDF score is given to words that appear frequently in a *specific* document but rarely across the *entire corpus*, making them good indicators of the document's content.

We will use `Scikit-learn`'s `TfidfVectorizer` to implement TF-IDF.
"""

from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

documents = [
    "The cat sat on the mat",
    "The dog ate the cat",
    "The cat is a pet"
]

# Create a TfidfVectorizer object
# It will build a vocabulary and convert documents to TF-IDF vectors
tfidf_vectorizer = TfidfVectorizer()

# Fit the vectorizer to the documents and transform them into TF-IDF vectors
X_tfidf = tfidf_vectorizer.fit_transform(documents)

# Get the feature names (words in the vocabulary)
tfidf_feature_names = tfidf_vectorizer.get_feature_names_out()

print("Vocabulary (Feature Names):", tfidf_feature_names)
print("\nShape of the TF-IDF matrix (Documents x Vocabulary Size):", X_tfidf.shape)

# Convert the sparse matrix to a dense array for better readability
dense_tfidf_array = X_tfidf.toarray()

# Display the TF-IDF matrix using a Pandas DataFrame for clarity
tfidf_df = pd.DataFrame(dense_tfidf_array, columns=tfidf_feature_names, index=[f'Document {i+1}' for i in range(len(documents))])
print("\nTF-IDF Matrix:")
print(tfidf_df)

# Example for a new document
new_document_tfidf = ["A cat is a furry animal"]
new_document_tfidf_vector = tfidf_vectorizer.transform(new_document_tfidf)
new_document_tfidf_df = pd.DataFrame(new_document_tfidf_vector.toarray(), columns=tfidf_feature_names, index=['New Document'])
print("\nTF-IDF Representation for a new document:")
print(new_document_tfidf_df)

import matplotlib.pyplot as plt
import seaborn as sns

# Visualize the TF-IDF matrix as a heatmap
plt.figure(figsize=(10, 6))
sns.heatmap(tfidf_df, annot=True, cmap='viridis', fmt=".2f")
plt.title('TF-IDF Matrix Heatmap')
plt.xlabel('Terms (Words)')
plt.ylabel('Documents')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""The heatmap visually confirms what we discussed:

*   **Darker shades (higher values)** indicate words that are more important and distinctive to a particular document. For example, 'mat', 'on', and 'sat' are highly relevant to Document 1.
*   **Lighter shades (lower values)** indicate words that are less important or very common across documents, like 'the' (although still present).

This visualization helps quickly identify the key terms that differentiate one document from another in the corpus, based on their weighted importance.

### 2.3 Document Similarity using TF-IDF (Cosine Similarity)

One of the most powerful applications of numerical text representations like TF-IDF is the ability to quantify the similarity between documents. A common metric for this is **Cosine Similarity**.

**Cosine Similarity** measures the cosine of the angle between two non-zero vectors in a multi-dimensional space. The closer the cosine similarity is to 1, the smaller the angle and the higher the similarity between the two documents. A value of 0 indicates no similarity, and -1 indicates complete dissimilarity (though with TF-IDF vectors, which are non-negative, the range will typically be between 0 and 1).

It's calculated as:

$$ \text{Cosine Similarity}(A, B) = \frac{A \cdot B}{||A|| \cdot ||B||} = \frac{\sum_{i=1}^{n} A_i B_i}{\sqrt{\sum_{i=1}^{n} A_i^2} \sqrt{\sum_{i=1}^{n} B_i^2}} $$

Where:
*   $A$ and $B$ are the TF-IDF vectors for two documents.
*   $A_i$ and $B_i$ are the components of vectors A and B.
*   $A \cdot B$ is the dot product of the vectors.
*   $||A||$ and $||B||$ are the Euclidean (L2) norms of the vectors.
"""

from sklearn.metrics.pairwise import cosine_similarity

# Function to calculate and print cosine similarity between two document indices
def predict_document_similarity(doc_index_1, doc_index_2, tfidf_matrix, document_names=None):
    """
    Calculates and prints the cosine similarity between two documents from a TF-IDF matrix.

    Args:
        doc_index_1 (int): Index of the first document.
        doc_index_2 (int): Index of the second document.
        tfidf_matrix (np.array or sparse matrix): The TF-IDF matrix.
        document_names (list, optional): List of document names for better output. Defaults to None.
    """
    if doc_index_1 >= tfidf_matrix.shape[0] or doc_index_2 >= tfidf_matrix.shape[0]:
        print("Error: Document index out of bounds.")
        return

    # Reshape for cosine_similarity function if using single rows
    vector_1 = tfidf_matrix[doc_index_1].reshape(1, -1)
    vector_2 = tfidf_matrix[doc_index_2].reshape(1, -1)

    similarity = cosine_similarity(vector_1, vector_2)[0][0]

    name_1 = document_names[doc_index_1] if document_names else f"Document {doc_index_1 + 1}"
    name_2 = document_names[doc_index_2] if document_names else f"Document {doc_index_2 + 1}"

    print(f"Cosine Similarity between '{name_1}' and '{name_2}': {similarity:.4f}")

# --- Example Usage ---
print("\n--- Comparing Existing Documents ---")
predict_document_similarity(0, 1, X_tfidf, document_names=documents)
predict_document_similarity(0, 2, X_tfidf, document_names=documents)
predict_document_similarity(1, 2, X_tfidf, document_names=documents)

# --- Comparing a New Document to Existing Ones ---
print("\n--- Comparing a New Document to Existing Documents ---")
# For this, we need the TF-IDF vector of the new document
# We already calculated `new_document_tfidf_vector` in the previous cell

# To compare, we need to add the new document's TF-IDF vector to our matrix (temporarily)
# Or iterate and compare individually.
# Let's compare individually for clarity.

new_doc_name = "A cat is a furry animal"
print(f"New Document: '{new_doc_name}'")

# Iterate through existing documents and calculate similarity with the new document
for i, doc_text in enumerate(documents):
    existing_doc_vector = X_tfidf[i].reshape(1, -1)
    similarity_with_new = cosine_similarity(new_document_tfidf_vector, existing_doc_vector)[0][0]
    print(f"  Similarity with '{doc_text}': {similarity_with_new:.4f}")

"""## 3. Text Mining Applications: Sentiment Analysis

**Sentiment Analysis**, also known as opinion mining, is a subfield of NLP that aims to determine the emotional tone or opinion expressed in a piece of text. It's about figuring out if the communicated message is positive, negative, or neutral.

### Why is Sentiment Analysis Important?

*   **Business Intelligence**: Understand customer feedback on products/services, identify trends, and improve customer satisfaction.
*   **Social Media Monitoring**: Track public opinion about brands, political events, or social issues.
*   **Reputation Management**: Monitor and manage brand perception online.
*   **Market Research**: Gauge market sentiment and consumer preferences.

### Approaches to Sentiment Analysis

There are generally three main approaches to sentiment analysis:

1.  **Rule-Based Approaches**: These systems rely on a set of predefined rules, lexicons (word lists with associated sentiment scores), and linguistic features to determine sentiment.
2.  **Machine Learning Approaches**: These involve training classification models (e.g., Naive Bayes, SVM, Logistic Regression) on labeled datasets to predict sentiment.
3.  **Deep Learning Approaches**: More advanced methods using neural networks (e.g., LSTMs, Transformers) to learn complex patterns and contexts for sentiment prediction, often achieving state-of-the-art results.

### 3.1 Rule-Based Sentiment Analysis (VADER)

**Rule-based sentiment analysis** typically uses a lexicon or dictionary of words, each associated with a polarity score (positive, negative, neutral). The overall sentiment of a text is determined by aggregating the scores of the words it contains, often with rules for intensifiers, negations, and punctuation.

One popular and effective rule-based tool is **VADER** (Valence Aware Dictionary and sEntiment Reasoner), specifically designed for sentiment analysis of social media text. VADER is part of NLTK and provides scores for positive, negative, neutral, and a composite score that normalizes the sentiment to a range between -1 (most extreme negative) and +1 (most extreme positive).
"""

# Download VADER lexicon
import nltk
nltk.download('vader_lexicon')

from nltk.sentiment.vader import SentimentIntensityAnalyzer

sentences_for_sentiment = [
    "This movie was absolutely fantastic and I loved every minute of it!",
    "The food was terrible, and the service was equally bad.",
    "The plot was okay, but the acting could have been better.",
    "I am so happy and excited!",
    "I am so mad and upset!",
    "The weather is nice today."
]

# Initialize VADER sentiment intensity analyzer
analyzer = SentimentIntensityAnalyzer()

print("--- Sentiment Analysis using VADER ---")
for sentence in sentences_for_sentiment:
    vs = analyzer.polarity_scores(sentence)
    print(f"\nText: {sentence}")
    print(f"  Sentiment Scores: {vs}")
    if vs['compound'] >= 0.05:
        print("  Overall Sentiment: Positive")
    elif vs['compound'] <= -0.05:
        print("  Overall Sentiment: Negative")
    else:
        print("  Overall Sentiment: Neutral")

"""### 3.2 Machine Learning-Based Sentiment Analysis (Naive Bayes)

**Machine Learning approaches** to sentiment analysis involve training a classification model on a dataset of texts labeled with their sentiment (e.g., positive, negative, neutral). The model learns patterns from these labeled examples and can then predict the sentiment of new, unseen texts.

#### Naive Bayes Classifier

One of the simplest yet surprisingly effective algorithms for text classification is the **Naive Bayes Classifier**. It's based on Bayes' theorem with an assumption of independence among predictors (features). In the context of text, this means it assumes the presence of a particular word in a document is independent of the presence of other words, given the sentiment class.

**Steps involved:**
1.  **Data Collection and Labeling**: Obtain a dataset of text and its corresponding sentiment labels.
2.  **Text Preprocessing**: Clean the text (e.g., lowercasing, punctuation removal, stop word removal, tokenization).
3.  **Feature Extraction (Vectorization)**: Convert the text into numerical features (e.g., Bag-of-Words or TF-IDF).
4.  **Model Training**: Train a Naive Bayes classifier (or another ML model) on the features and labels.
5.  **Prediction and Evaluation**: Use the trained model to predict sentiment on new data and evaluate its performance.
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report
import re
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk

# Ensure NLTK data is downloaded for preprocessing
try:
    stopwords.words('english')
except LookupError:
    nltk.download('stopwords')

# --- 1. Create a Sample Labeled Dataset ---
data = {
    'text': [
        "I love this product, it's amazing!",
        "This is the worst experience ever, so disappointed.",
        "It's okay, not great but not terrible either.",
        "Fantastic service, highly recommend.",
        "Absolutely dreadful, waste of money.",
        "Pretty good, I'm satisfied.",
        "Could be better, but it's acceptable.",
        "The best purchase of the year!",
        "Never again, completely dissatisfied.",
        "Neutral review, nothing special."
    ],
    'sentiment': [
        'positive', 'negative', 'neutral', 'positive', 'negative',
        'positive', 'neutral', 'positive', 'negative', 'neutral'
    ]
}
df = pd.DataFrame(data)

print("Original Dataset:")
print(df)

# --- 2. Text Preprocessing Function ---
def preprocess_text(text):
    # Lowercasing
    text = text.lower()
    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))
    # Tokenize
    tokens = word_tokenize(text)
    # Remove stop words
    stop_words = set(stopwords.words('english'))
    filtered_tokens = [word for word in tokens if word not in stop_words]
    return " ".join(filtered_tokens)

df['processed_text'] = df['text'].apply(preprocess_text)

print("\nProcessed Dataset:")
print(df[['text', 'processed_text', 'sentiment']])

# --- 3. Feature Extraction (Vectorization using CountVectorizer) ---
vectorizer_ml = CountVectorizer()
X_ml = vectorizer_ml.fit_transform(df['processed_text'])
y_ml = df['sentiment']

print("\nShape of Feature Matrix:", X_ml.shape)

# --- 4. Train/Test Split ---
X_train, X_test, y_train, y_test = train_test_split(X_ml, y_ml, test_size=0.3, random_state=42)

print(f"\nTraining samples: {X_train.shape[0]}") # Corrected line
print(f"Testing samples: {X_test.shape[0]}")   # Corrected line

# --- 5. Train a Naive Bayes Model ---
model = MultinomialNB()
model.fit(X_train, y_train)

print("\nNaive Bayes Model trained successfully.")

# --- 6. Prediction and Evaluation ---
y_pred = model.predict(X_test)

print("\nModel Evaluation:")
print(f"Accuracy: {accuracy_score(y_test, y_pred):.2f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# --- Example Prediction on new text ---
print("\n--- Predicting Sentiment for New Text ---")
new_texts = [
    "This product is absolutely amazing!",
    "I completely hate this service.",
    "It's just average."
]

for text in new_texts:
    processed_new_text = preprocess_text(text)
    # Transform new text using the *same* vectorizer fitted on training data
    vectorized_new_text = vectorizer_ml.transform([processed_new_text])
    prediction = model.predict(vectorized_new_text)[0]
    print(f"Text: '{text}' -> Predicted Sentiment: '{prediction}'")

"""Gerne, ich erkläre Ihnen den Unterschied zwischen regelbasierter und maschineller Lern-Sentimentanalyse:

Regelbasierte Sentimentanalyse (Regelbasiert)
Ansatz: Diese Methode verwendet vordefinierte Regeln, Lexika (Wörterbücher mit Sentiment-Scores) und linguistische Muster. Es werden Listen von Wörtern erstellt, die positive, negative oder neutrale Bedeutungen haben, zusammen mit Regeln, die festlegen, wie diese Wörter im Kontext die Gesamtstimmung beeinflussen (z.B. Verstärkung durch Adverbien, Negationen).
Wie es funktioniert: Die Analyse erfolgt durch Zählen und Aggregieren der Sentiment-Scores der Wörter in einem Text, unter Berücksichtigung der festgelegten Regeln. Ein bekanntes Beispiel ist VADER.
Vorteile: Oft einfach zu implementieren, transparent und gut interpretierbar. Es benötigt keine großen Mengen an Trainingsdaten.
Nachteile: Kann unflexibel sein und Schwierigkeiten mit Ironie, Sarkasmus oder neuen Ausdrücken haben. Die Erstellung und Pflege der Regeln und Lexika kann aufwendig sein und erfordert Domänenwissen.
Maschinelle Lern-Sentimentanalyse (Machine Learning)
Ansatz: Hierbei wird ein Algorithmus (z.B. Naive Bayes, Support Vector Machines, neuronale Netze) darauf trainiert, Sentiment anhand von Beispielen zu erkennen. Der Algorithmus lernt Muster und Zusammenhänge zwischen den Textmerkmalen und den Sentiment-Labels.
Wie es funktioniert: Zuerst wird ein Datensatz von Texten mit den zugehörigen Sentiment-Labels (z.B. 'positiv', 'negativ', 'neutral') benötigt. Der Text wird vorverarbeitet (tokenisiert, Stoppwörter entfernt, etc.) und in numerische Merkmale umgewandelt (z.B. Bag-of-Words, TF-IDF). Dann wird ein Modell mit diesen Merkmalen und Labels trainiert. Das trainierte Modell kann anschließend das Sentiment für neue, ungesehene Texte vorhersagen.
Vorteile: Kann komplexere Muster erkennen und ist oft robuster gegenüber sprachlichen Nuancen wie Ironie. Es ist flexibler und kann an verschiedene Domänen angepasst werden, wenn ausreichend Trainingsdaten vorhanden sind.
Nachteile: Erfordert einen großen, gut annotierten Datensatz zum Training. Die Modelle können 'Black Boxes' sein, deren Entscheidungen schwer zu interpretieren sind. Die Leistung hängt stark von der Qualität und Quantität der Trainingsdaten ab.
Zusammenfassend lässt sich sagen:

Regelbasierte Ansätze basieren auf explizitem Wissen und vordefinierten Regeln.
Maschinelle Lern- Ansätze lernen implizite Muster und Regeln aus Daten.
"""

