# -*- coding: utf-8 -*-
"""SPARKS_Project_1_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12COOxPaHNLDCJxRMXHYqtuSr5_rPdt5M
"""



"""# Final Project: Social Media Advertising Analysis
**Course:** Media & Data Science - 5th Semester
**University:** SPARKS University, Munich

---

## 1. Project Overview
You will analyze a dataset of 150,000 social media campaigns. Your goal is to identify which channels and audience segments yield the best ROI and Conversion Rates.

### Dataset
The `social_media_advertising.csv` contains performance metrics including:
- **Channel_Used**: Instagram, Facebook, etc.
- **Conversion_Rate**: Percentage of clicks resulting in a result.
- **ROI**: Return on Investment.
- **Engagement_Score**: 1-10 scale.

---

## 2. Environment Setup & Data Loading
First, we need to import our tools and load the dataset into a Pandas DataFrame.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# URL to the raw CSV
url = 'https://raw.githubusercontent.com/katjanieberle/sparks/main/social_media_advertising.csv'

# TASK: Load the dataset using pandas
df = pd.read_csv(url)

print("Dataset Shape:", df.shape)
display(df.head())

"""### Task 3.1: Initial Inspection
Use `.info()` and `.describe()` to understand the data.

**Question to answer:** Which column has the highest standard deviation in performance? Are there any columns that might need data type conversion (like Acquisition_Cost if it contains currency symbols)?
"""

# YOUR CODE HERE
# 1. Print info

# 2. Print descriptive statistics

"""### Task 3.2: Channel Performance
Visualize the average `ROI` per `Channel_Used` using a bar plot. Which channel appears to be the most profitable on average?
"""

# YOUR CODE HERE
# Use sns.countplot() to visualize the 'Purchased' column

"""### Task 3.3: Relationship Analysis
Create a scatter plot showing `Engagement_Score` vs `Conversion_Rate`, colored by `Channel_Used`.

**Insight:** Is a high engagement score a strong linear predictor for a high conversion rate in this dataset?

### Task 3.4: Distribution Analysis (Histograms)
To understand the spread of your marketing metrics, visualize the distribution of `ROI` and `Conversion_Rate`.

**Goal:** Identify if the data is normally distributed or skewed. Use `sns.histplot` with `kde=True`.
"""

# YOUR CODE HERE
# Create a figure with two subplots for ROI and Conversion_Rate

"""### Task 3.5: Identifying Outliers (Boxplots)
Use boxplots to compare the `Engagement_Score` across different `Campaign_Goal` categories.

**Interpretation:** Look for the 'whiskers' and dots. Are there specific goals that consistently produce outlier results in engagement?
"""

# YOUR CODE HERE
# Use sns.boxplot(x='Campaign_Goal', y='Engagement_Score', data=df)
# Tip: Rotate x-labels if they overlap

"""### Task 3.6: Correlation Heatmap
Calculate the correlation matrix for all numerical features and visualize it using a heatmap.

**Critical Thinking:** Identify the strongest positive and negative correlations. Does `Acquisition_Cost` (after cleaning) correlate with `ROI`?
"""

# YOUR CODE HERE
# 1. Select only numerical columns
# 2. Compute .corr()
# 3. Plot with sns.heatmap(annot=True)

"""### Task 3.7: Interpretation & Business Case
Based on all previous plots, write a short paragraph answering the following:
*Which Target Audience and Channel combination would you recommend for a 'Product Launch' to maximize ROI? Justify your answer using the trends seen in your charts.*
"""

# YOUR CODE HERE
# Use sns.scatterplot() with hue='Purchased'

"""## 4. Submission Instructions

To successfully complete this project, you must submit your results via two channels:

### A. GitHub Repository
1. Create a public repository on GitHub named `SPARKS_EDA_Project_[YourID]`.
2. Upload this `.ipynb` file with all outputs saved.
3. Include a `README.md` file summarizing your key findings from the EDA.

### B. ZIP Archive
Upload a ZIP file to the university portal containing:
1. The `.ipynb` notebook file.
2. The `README.md` (exported as PDF).
3. Any additional assets (plots, exported CSVs).

### LLM Usage Transparency
If you used an LLM (e.g., ChatGPT, Claude, Gemini) to assist with coding or analysis:
- **Transparency:** Clearly state at the bottom of your notebook which parts were generated/assisted by an AI.
- **Prompts:** List the specific prompts you used.
- **Reflections:** Describe at least one problem or hallucination you encountered with the LLM (e.g., incorrect syntax, logical errors, or deprecated library functions).

### Project Defense
Be prepared for a **15-minute online defense**. You will be asked to live-code a small visualization and explain your correlation analysis results.

**Good luck!**
"""